### ISSUE TITLE
connmark

### ISSUE THREAD

**Issue by ktsaou** [ktsaou/firehol#23]
connmark has several issues.

- [x] mark, save and restore are executed on every packet, while mark and save should be applied to new packets and restore on established and related packets.

- [x] saving and restoring is very confusing. We should add rules at the beginning and the end of the firewall, if a connmark command has been used.

- [x] when load balancing multiple interfaces, the commands used are again cryptic. The user has to connmark on the PREROUTING with inface and on POSTROUTING with outface.

**Comment by ktsaou** [comment]
@philwhineray I need your opinion on this:

Now with the link-balancer, it would be nice to allow policy based routing using marks.

However I have already used connmarks for deciding which gateway should be used when replying back.

I think we should use masks on marks to separate plain marks from connmarks.

Why we need this?

Connmarks and marks overwrite each other. So when you assign a connmark you loose the mark and vice versa. I think we should allow them to co-exist. So, for link-balancer needs you could have a mark marking the interface traffic came in, but for FireQOS you could mark packets for classifying traffic.

iptables allows this using masks. For example:

- connmark 1 should be 0x00000001 with mask 0x000000ff
- but mark 1 should be 0x00000100 with mask 0xffffff00

This way, FireHOL, FireQOS and LinkBalancer will provide matches for both `connmark` and `mark` and internally use the same masks for each.

I think we should separate the 32 bit marks in 4 sections:

- connmarks with mask 0x000000ff
- routemarks with mask 0x0000ff00
- qosmarks with mask 0x00ff0000
- firewallmarks with mask 0xff000000

All tools should handle all 4 of them, like this:

- the keywords `connmark`, `routemark`, `qosmark` and `fwmark` should be handled by all for assuming the correct mask.
- for each of the above the user should specify the mark value in the range 0-255 and the tool internally should shift it to get it in the relative range. Thus:
  - `connmark 1` will mark 0x00000001/0x000000ff
  - `routemark 1` will mark 0x00000100/0x0000ff00
  - `qosmark 1` will mark 0x00010000/0x00ff0000
  - `fwmark 1` will mark 0x01000000/0xff000000

This way, all marks could co-exists and be independent. A connection could have connmark 2, routemark 4, qosmark 7 and fwmark 12 at the same time.

We could also permanently save and restore marks from/to connmarks in firehol, so that all these marks are always permanent to all connections (this also has the benefit we will only need to mark NEW packets in firehol - ESTABLISHED and RELATED packets will automatically get the mark from their connection).

This is a big change in marks and connmarks.
What do you think?

**Comment by ktsaou** [comment]
Keep in mind also that years ago I was thinking to use marks for another purpose.

Now you cannot assign a mark a specific firehol statement. You cannot say for example:

```sh
server smtp accept set mark 2
```

so that in QoS you can classify this specific traffic. Now, in order to assign a mark to it, you have to use the `mark` helper at the top of firehol and match the smtp traffic again.

I believed then that FireHOL should apply all its rules on the `mangle` table to just assign marks. Then the `filter` table could just use the marks to accept, reject or drop the traffic.

Possibly this could also be helpful on NAT.

It would be perfect though for QoS. In this scenario, FireHOL could just save all the marks it has assigned for each statement and in FireQOS you could just say which services you want in which class.

This approach will have to use a vast amount of marks, one for each firehol statement and it will require quite a re-factoring on firehol.

I mention it just because it is conflicting with the new use of marks I proposed above.

Generally, I still believe that marks could be a solution to an even simpler way of managing and configuring firewalls, QoS and routing. But I don't think we are there yet. Even if we try this now, I have the filling we are going to hit a lot of dead-ends.

So, my proposal still applies.

**Comment by philwhineray** [comment]
Hi Costa

You have clearly given this quite a bit of thought, so you will excuse me if I am a bit behind. I am typing as I think so I hope this comes out useful.

The problem you are describing, I think, is that the user might want to apply a mark for some QOS purpose and at the same time apply a mark from some routing purpose. The raw commands enable the marks to be used as a bitfield which is what makes this possible. The question then is how to best divide up the 32 bit number to enable best use of it.

Does the distinction between connmark and mark do anything useful? If we appply the save/restore logic automatically at the end, we can treat them as a common thing and as if they will always be equal, right? If so I agree and think this is exactly the sort of thing that can be usefully hidden from the user and it also reclaims 8 bits from the `connmark`, `routemark`, `qosmark`, `fwmark` list.

Another option which would maybe need more thought, would be a common marks.conf which all programs would read. This would serve two purposes - to provide symbolic names to marks, which I think would be nice anyway, and to divide up the 32 bits so that if I needed more of one type of mark and less of another then this could be done, probably automatically. It would also allow us to add new types of mark without adding a new command. Something like:

~~~~
markdef qos bulk
markdef qos interactive
markdef route 
~~~~

The second field (mark group?) is used to calculate the required masks only - the 3rd field (mark name?) must be unique and is used to lookup mask and value when it is used.

Errors can be generated if the user tries to specify something impossible e.g. tries to create 30 mark groups with 1 entry and another with 4 or more. Because the space can be optimised, the user can easily create names that are either exclusive (within a group) or additive (between groups) for their own purposes as well as the ones we envisage.

Also, this optimisation means internal use should be possible as well as user-defined e.g. your ideas for using `mangle` to mark and `filter` to drop and also my possible use for interaction with `ebtables` for bridges, where the behaviour should be automatic. There is only an error if the user defines so many marks that there are not enough left, which will be an impossible situation anyway.

**Comment by ktsaou** [comment]
Ok. Nice. I really like this marks.conf thing...

I create this script:

```sh
#!/bin/bash

declare -A MARKS_BITS=()
declare -A MARKS_MASKS=()
declare -A MARKS_MAX=()

MARKS_TOTAL_BITS=0

error() {
	echo >&2 "ERROR: ${*}"
	exit 1
}

# taken from http://stackoverflow.com/questions/109023/how-to-count-the-number-of-set-bits-in-a-32-bit-integer
# and http://books.google.gr/books?id=iBNKMspIlqEC&pg=PA66&redir_esc=y#v=onepage&q&f=false
# counts the number of bits set in a number
numberofbits() {
	local x="${1}"

	local x=$[ x - ( (x >> 1) & 0x55555555) ]
	local x=$[ (x & 0x33333333) + ( (x >> 2) & 0x33333333) ]
	local x=$[ (x + (x >> 4) ) & 0x0F0F0F0F ]
	local x=$[ x + (x >> 8) ]
	local x=$[ x + (x >> 16) ];
	local bits=$[ x & 0x0000003F ]
	echo $bits
}

# taken from http://www.skorks.com/2010/10/write-a-function-to-determine-if-a-number-is-a-power-of-2/
# checks if a number is power of 2
ispoweroftwo() {
	local num="${1}"

	test ! $num = 0 -a $[num & (num - 1)] = 0 && return 0
	return 1
}

markdef() {
	# echo "${FUNCNAME} ${*}"
	local name="${1}"; shift
	local max="${1}"; shift

	if [ "${max}" = "rest" ]
	then
		local max=$[ 1 << (32 - MARKS_TOTAL_BITS) ]
	fi

	if ! ispoweroftwo $max
	then
		error "Max value $max of mark '$name' is not a power of 2."
	fi

	# it will be from 0 to max - 1
	max=$[ max - 1 ]

	if [ $max -lt 1 -o $max -gt $[ 0xffffffff ] ]
	then
		error "Max value $max of mark '$name' is out of bounds."
	fi

	# prevent a fork
	bits=$(numberofbits $max)

	if [ $bits -eq 0 ]
	then
		error "INTERNAL ERROR: Cannot figure out the bits set of value $max."
	fi

	if [ $[ bits + MARKS_TOTAL_BITS ] -gt 32 ]
	then
		error "Too many masks were requested. Cannot proceed. Please use fewer."
	fi

	# find its mask
	# we have all the bits we need set in $mark
	# just shift it to the right position.
	local mask=$[ max << MARKS_TOTAL_BITS ]
	MARKS_TOTAL_BITS=$[ MARKS_TOTAL_BITS + bits ]

	MARKS_MAX[$name]=$max
	MARKS_BITS[$name]=$bits
	MARKS_MASKS[$name]=$(printf "0x%08x" $mask)

	echo "Mark $name with max number of marks $[MARKS_MAX[$name] + 1] (from 0 to ${MARKS_MAX[$name]}), uses ${MARKS_BITS[$name]} bits and has mask ${MARKS_MASKS[$name]}"
}

# validation
#for i in `seq 1 32`
#do
#	markdef test$i $[ 1 << i ]
#done

#markdef connmark 256
#markdef routemark 256
#markdef qosmark 256
#markdef fwmark 256

markdef routemark 64
markdef qosmark 32
markdef fwmark 32
markdef ifmark 128
markdef stmark rest

echo
echo "# Final definitions"
declare -p MARKS_BITS MARKS_MASKS MARKS_MAX
```

a run gives this response:

```sh
Mark routemark with max number of marks 64 (from 0 to 63), uses 6 bits and has mask 0x0000003f
Mark qosmark with max number of marks 32 (from 0 to 31), uses 5 bits and has mask 0x000007c0
Mark fwmark with max number of marks 32 (from 0 to 31), uses 5 bits and has mask 0x0000f800
Mark ifmark with max number of marks 128 (from 0 to 127), uses 7 bits and has mask 0x007f0000
Mark stmark with max number of marks 512 (from 0 to 511), uses 9 bits and has mask 0xff800000

# Final definitions
declare -A MARKS_BITS='([fwmark]="5" [qosmark]="5" [routemark]="6" [stmark]="9" [ifmark]="7" )'
declare -A MARKS_MASKS='([fwmark]="0x0000f800" [qosmark]="0x000007c0" [routemark]="0x0000003f" [stmark]="0xff800000" [ifmark]="0x007f0000" )'
declare -A MARKS_MAX='([fwmark]="31" [qosmark]="31" [routemark]="63" [stmark]="511" [ifmark]="127" )'
```

What is each mark of them?

1. `routemark` is todays connmark, used exclusively for link-balancer.
2. `qosmark` to be used for FireQOS.
3. `fwmark` to be used by FireHOL for user-controlled marks.
4. `ifmark` and `stmark` can be used internally by FireHOL for moving all matches to `mangle`. `ifmark` will be used for counting interfaces and routers and `stmark` will be used for counting statements within each interface and router. We need this separation to speed up the `filter` table. We will branch once per interface and router and then take action per statement.

As you can see there aren't enough marks for everything. up to 512 FireHOL statements per interface and router, up to 128 interfaces and routers, up to 64 link-balancer interfaces, up to 32 user-defined FireQOS marks and up to 32 user-defined FireHOL marks.

The only variations a user may request is more `stmarks` and less `ifmarks`, more `routemarks` and less `fwmarks`... we are talking about very little variations though. Just a bit to move from one category to another...

What do you think?

**Comment by ktsaou** [comment]
Probably a more sensible split is this:

```sh
markdef connmark 64
markdef usermark 128
markdef ifmark 256
markdef stmark rest
```

which gives:

```sh
Mark connmark with max number of marks 64 (from 0 to 63), uses 6 bits and has mask 0x0000003f
Mark usermark with max number of marks 128 (from 0 to 127), uses 7 bits and has mask 0x00001fc0
Mark ifmark with max number of marks 256 (from 0 to 255), uses 8 bits and has mask 0x001fe000
Mark stmark with max number of marks 2048 (from 0 to 2047), uses 11 bits and has mask 0xffe00000

Final definitions
declare -A MARKS_BITS='([connmark]="6" [stmark]="11" [usermark]="7" [ifmark]="8" )'
declare -A MARKS_MASKS='([connmark]="0x0000003f" [stmark]="0xffe00000" [usermark]="0x00001fc0" [ifmark]="0x001fe000" )'
declare -A MARKS_MAX='([connmark]="63" [stmark]="2047" [usermark]="127" [ifmark]="255" )'
```

Now we leave the user with 128 marks which he/she can use in any tool he likes.

**Comment by ktsaou** [comment]
Updated the script to keep track of the bits values should be shifted to put in place, for all marks:

```sh
#!/bin/bash

declare -A MARKS_BITS=()
declare -A MARKS_MASKS=()
declare -A MARKS_MAX=()
declare -A MARKS_SHIFT=()

MARKS_TOTAL_BITS=0

error() {
	echo >&2 "ERROR: ${*}"
	exit 1
}

# taken from http://stackoverflow.com/questions/109023/how-to-count-the-number-of-set-bits-in-a-32-bit-integer
# and http://books.google.gr/books?id=iBNKMspIlqEC&pg=PA66&redir_esc=y#v=onepage&q&f=false
# counts the number of bits set in a number
numberofbits() {
	local x="${1}"

	local x=$[ x - ( (x >> 1) & 0x55555555) ]
	local x=$[ (x & 0x33333333) + ( (x >> 2) & 0x33333333) ]
	local x=$[ (x + (x >> 4) ) & 0x0F0F0F0F ]
	local x=$[ x + (x >> 8) ]
	local x=$[ x + (x >> 16) ];
	local bits=$[ x & 0x0000003F ]
	echo $bits
}

# taken from http://www.skorks.com/2010/10/write-a-function-to-determine-if-a-number-is-a-power-of-2/
# checks if a number is power of 2
ispoweroftwo() {
	local num="${1}"

	test ! $num = 0 -a $[num & (num - 1)] = 0 && return 0
	return 1
}

markdef() {
	# echo "${FUNCNAME} ${*}"
	local name="${1}"; shift
	local max="${1}"; shift

	if [ "${max}" = "rest" ]
	then
		local max=$[ 1 << (32 - MARKS_TOTAL_BITS) ]
	fi

	if ! ispoweroftwo $max
	then
		error "Max value $max of mark '$name' is not a power of 2."
	fi

	# it will be from 0 to max - 1
	max=$[ max - 1 ]

	if [ $max -lt 1 -o $max -gt $[ 0xffffffff ] ]
	then
		error "Max value $max of mark '$name' is out of bounds."
	fi

	# prevent a fork
	bits=$(numberofbits $max)

	if [ $bits -eq 0 ]
	then
		error "INTERNAL ERROR: Cannot figure out the bits set of value $max."
	fi

	if [ $[ bits + MARKS_TOTAL_BITS ] -gt 32 ]
	then
		error "Too many masks were requested. Cannot proceed. Please use fewer."
	fi

	# find its mask
	# we have all the bits we need set in $mark
	# just shift it to the right position.
	local mask=$[ max << MARKS_TOTAL_BITS ]

	MARKS_SHIFT[$name]=${MARKS_TOTAL_BITS}
	MARKS_MAX[$name]=$max
	MARKS_BITS[$name]=$bits
	MARKS_MASKS[$name]=$(printf "0x%08x" $mask)

	echo "Mark $name with $[MARKS_MAX[$name] + 1] possible values (from 0 to ${MARKS_MAX[$name]}), uses ${MARKS_BITS[$name]} bits, has mask ${MARKS_MASKS[$name]} and values should be shifted by ${MARKS_SHIFT[$name]} bits"

	MARKS_TOTAL_BITS=$[ MARKS_TOTAL_BITS + bits ]
}

# validation
#for i in `seq 1 32`
#do
#	markdef test$i $[ 1 << i ]
#done

#markdef connmark 256
#markdef routemark 256
#markdef qosmark 256
#markdef fwmark 256

#markdef routemark 64
#markdef qosmark 32
#markdef fwmark 32
#markdef ifmark 128
#markdef stmark rest

markdef connmark 64
markdef usermark 128
markdef ifmark 256
markdef stmark rest

echo
echo "# Final definitions"
declare -p MARKS_BITS MARKS_MASKS MARKS_MAX MARKS_SHIFT
```

**Comment by ktsaou** [comment]
@philwhineray, I will open a new thread for two tasks:

1. Using marks at the FireHOL core
2. Modularizing FireHOL to support the forthcoming nfmarks.

So, this thread remains connmark and marks related for all uses except FireHOL core.

I have already started experimenting with permanent connmarks and marks, using the approach that the 'mark' keyword in all tools refers to bitmasked 'usermark' and connmark refers to bitmarked 'connmark'.

I hope I'll have something ready by the end of the week.
Do you want me to open a new branch for them, or just commt them in the main source tree?

**Comment by ktsaou** [comment]
Keep in mind that for this purpose the changeset is not so significant...

**Comment by ktsaou** [comment]
Just pushed the `marks` branch.

I tested that the generated statements are accepted for FireHOL, FireQOS and LinkBalancer. I have not yet tested if they work though.

For all tools:

- `mark` actually means: usermark bitmask
- `connmark` means: connmark bitmask
- `rawmark` means no bitmasking

Also, only FireHOL processes /etc/firehol/masks.conf and generated /var/spool/firehol/masks.conf.

The other 2 tools use only /var/spool/firehol/masks.conf.

Internally, the defaults for all 3 tools is the same (64 connmarks and 128 usermarks).

**Comment by philwhineray** [comment]
Nice work. I don't have much time to look at this properly right now but will do so as soon as I can.

I can make the branch auto-build tar-files on the servers if you like, or we can just leave it as-is for now.

**Comment by ktsaou** [comment]
It ok Phil as it is.
I will test it and then merge it to the main tree.

**Comment by ktsaou** [comment]
@philwhineray I tested it and it works for all tools. Marks and Connmarks are now be combined on the same mark value, are saved and restored and all tools match them properly.

I also changed the implementation of TPROXY  ( #25 ) in firehol to use the maximum usermark instead of a fixed one.
