### ISSUE TITLE
Allow stopping fireqos based on config file or specific interface

### ISSUE THREAD

**Issue by nemphys** [ktsaou/firehol#32]
Hi, first of all I must say I am totally impressed by your work!

One easy change that would be useful is to give the fireqos script the ability to stop all shaping (like it does with the stop parameter) but only for a specific interface (or a specific configuration file that defines rules for specific interfaces).

I have 2 ADSL connections, and I would like to start and stop shaping on the with ppp/ip-up.d scripts. It is possible to start shaping on each of the 2 separately using separate config files, but from what I see it is not possible to stop shaping just for 1 of the interfaces (it's either all or nothing).

I could always modify the script myself, but I am totally worthless in bash scripting and I would have to apply the patch on every update.

**Comment by nemphys** [comment]
Any news on this one?
I implemented the change back in September 2014, but I hate to have to do it every time :-)

**Comment by ktsaou** [comment]
Δημήτρη σ' ευχαριστώ για τα καλά σου λόγια...

OK back to English. For some reason I didn't notice this request. Sorry.

Just pushed the feature you need.
To stop a specific interface, just append the interface device name(s) to the stop command. FireQOS will stop both inbound and outbound QoS on this interface.

Example:

```sh
fireqos stop ppp0
```

In this example, fireqos will stop both inbound and outbound QoS rules on ppp0.

If it OK, please close this issue.
Thanks.

**Comment by nemphys** [comment]
That was fast :-)
Seems to work fine, thanks again for the great work!
