### ISSUE TITLE
Ruleset for bypassing transparent proxy

### ISSUE THREAD

**Issue by oneguynick** [ktsaou/firehol#44]
I have searched in vain for a way to allow a single IP address to bypass the transparent proxy. This causes issues with devices which cannot utilize proxies.

**Comment by ktsaou** [comment]
Happy New Year,

This is what I use:

```sh
ipv4 transparent_squid 3127 "costa root squid" \
        inface "eth+ ppp+ tun+" \
        src "10.0.0.0/24 192.168.0.0/24" \
        dst not "83.235.24.51 83.235.24.52 83.235.24.233 83.235.24.227"
```

This catches all traffic:

* from interfaces eth+ ppp+ and tun+
* and from source IPs in subnets 10.0.0.0./24 or 192.168.0.0/24
* and going to ALL web servers EXCEPT these: 83.235.24.51 83.235.24.52 83.235.24.233 83.235.24.227

Also the local users: costa, root and squid are excluded. All other local users will go through the proxy.

You can of course use `src not` to exclude some clients, but you cannot have both positive and negative rules on the same statement.

For example, this statement will send all client on eth0 through the proxy, except 10.1.1.1 and 10.1.1.2:

```sh
ipv4 transparent_squid 3127 "root squid proxy" \
        inface "eth0" \
        src not "10.1.1.1 10.1.1.2"
```

However this statements does not seem right to me:

> This causes issues with devices which cannot utilize proxies.

I have never experienced any issues with any web client device, not being able to use the proxy. The proxy acts like a web server. The clients cannot know if they are talking to the real web server or a transparent proxy. This is why it is called "transparent".

What problem do you experience?

**Comment by oneguynick** [comment]
Happy New Year to you also and thank you for such a quick response. It is actually my Wemo, Sony Dash, and Philips Hue that all have issues with SQUID proxy servers. Philips actually has a documented issue. Very odd I agree, but is such.

I was able to test these rules and they work. I am now able to change the colour of my lights from work. A very important feature! Thank you again for your help.
