### ISSUE TITLE
Optimizing FireHOL (make it faster)

### ISSUE THREAD

**Issue by ktsaou** [ktsaou/firehol#45]
Branched from #23 
Modularization moved to #48 

This is about optimizing firehol.

**Comment by ktsaou** [comment]
@philwhineray you will probably want to examine commit https://github.com/ktsaou/firehol/commit/538e8b7b9a6e3048517f00a38aae361601c0707d

I have managed to gain almost twice the speed in firehol. In my machine the it was needing 14 seconds to run the firewall, now it needs 7.5

At my office it was needing 4 minutes and 39 seconds, now it needs 2 minutes and 23 seconds.

The generated rules are the same in all cases I tried.
Let me know if you find anything.

**Comment by philwhineray** [comment]
@ktsaou sounds like a very good improvement

Some of my tests fail because the ipv4/ipv6 namespace is not being reset properly, for example:

~~~~
version 6

interface eth0 myeth0
        policy deny
        ipv4 client ssh accept src "10.0.0.1"
        ipv6 client tftp accept src "fe80::/64"
~~~~

Gives an error `Cannot use namespace ipv6 within ipv4`.

I will take a look to see if I can suggest a change in keeping with your new code but I may run out of time today.

**Comment by philwhineray** [comment]
I think all that is needed for the above is this:

~~~~
diff --git a/sbin/firehol.in b/sbin/firehol.in
index 62b9104..7ab7a52 100755
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -1366,9 +1366,8 @@ push_namespace() {
 }
 
 pop_namespace() {
+       FIREHOL_NS_STACK=(${FIREHOL_NS_STACK[@]:1})
        FIREHOL_NS_CURR="${FIREHOL_NS_STACK[0]}"
-       unset FIREHOL_NS_STACK[0]
-       FIREHOL_NS_STACK=("${FIREHOL_NS_STACK[@]}")
 
        #echo >&2 "${FUNCNAME} ${FIREHOL_NS_CURR} == ${FIREHOL_NS_STACK[*]}"
        return 0
~~~~

**Comment by ktsaou** [comment]
Thanks. My fault.

**Comment by ktsaou** [comment]
@philwhineray one key change in the optimization was that `eval_param()` was removed and replaced with static bash search/replace at https://github.com/ktsaou/firehol/commit/538e8b7b9a6e3048517f00a38aae361601c0707d#diff-ba8443e39a0d5da59eced1d750693e02R6313

If any user is using functions in src/dst IPs, his firewall will not be activated.
I think however this was just used internally.

**Comment by philwhineray** [comment]
Actually, my suggestion leaves this broken:

~~~~
version 6

ipv4 mac 10.0.0.1 00:01:01:00:00:e6
ipv6 mac fe80::/64 00:01:01:00:00:e6

interface eth0 myeth0
~~~~

This is the better definition, ensuring peek_namespace() remains unused so it can be removed:

~~~~
pop_namespace() {
        FIREHOL_NS_STACK=(${FIREHOL_NS_STACK[@]:1})
        FIREHOL_NS_CURR=${FIREHOL_NS_STACK[0]-${FIREHOL_DEFAULT_NAMESPACE}}

        #echo >&2 "${FUNCNAME} ${FIREHOL_NS_CURR} == ${FIREHOL_NS_STACK[*]}"
        return 0
}
~~~~

**Comment by philwhineray** [comment]
Yes, I saw the removal of eval_param().

I don't use it in any config of my own. I don't think I documented it, either, so I would be very surprised if someone is using this behaviour.

I agree with removing it for now, if we find a problem we can see then what to do.

**Comment by philwhineray** [comment]
Retested with latest changes, all the problems I saw on the `marks branch` seem resolved by your commits.

**Comment by ktsaou** [comment]
ok. I merge it then...
