### ISSUE TITLE
Mark handling in firehol

### ISSUE THREAD

**Issue by philwhineray** [ktsaou/firehol#50]
A question based on the [netfilter flow diagram](http://upload.wikimedia.org/wikipedia/commons/3/37/Netfilter-packet-flow.svg) - would it make more sense to do `--save-mark` with `-t filter -A INPUT` rather than `-t mangle`? As `-t filter` is processed later it would ensure the mark is saved after all other processing.

I would also quite like to consider a stateless option to the mark helpers. This is because I want to mark connections based on physdev but this will only be available when packets originate from that device. The stateful implementation means that only outgoing connections will have a mark set.

If the match is stateless then connections starting outside will be matched, just the first packet will be missed. Obviously the mark can be applied with the `iptables` helper:

~~~~
wlanmark="$(mark_value qosmark 1)"
iptables -t mangle -A PREROUTING -m physdev --physdev-in wlan0 -j MARK --set-mark ${wlanmark}
~~~~

I think it would be nice to provide an option though, something like `custommark anystate qosmark 1 FORWARD physin wlan0`.

The problem is that either method will have the mark overwritten by the save/restore code, since the old value will be restored on egress.

I don't know if always saving/restoring marks is slower than first testing the state. If there is not much difference then we could just always save and restore. If there is a significant difference then we could either:

* Change save/restore behaviour when an anystate mark was made or on an option
* Change the code so that it saves only if the mark is non-zero and the connmark is zero, rather than by connection tracker state.
* Explicitly save to connmark after an anystate mark to ensure it is consistent.

An advantage of changing the save/restore behaviour for everything would be that it would allow for the possibility of changing the mark on a connection. The current code guarantees that once set to the connection the same value will always be restored even if the user tries to change it.

**Comment by ktsaou** [comment]
Let me also add that there may be a need for marks that will not be saved/restored at all. This could be achieved by adding a `nosave` or `norestore` option to `markdef`. This will make the specific mark type be excluded from saving and restoring (save and restore will save and restore marks with a bitmask of only the mark types that should be saved and restored).

If we do this, then based on your post above, I understand that the only thing we have to support is stateless marks. Am I right?

**Comment by ktsaou** [comment]
> A question based on the netfilter flow diagram - would it make more sense to do --save-mark with -t filter -A INPUT rather than -t mangle? As -t filter is processed later it would ensure the mark is saved after all other processing.

@philwhineray I think this is wrong for 2 reasons:

1. there is nothing that can change the mark between mangle and filter
2. filter has no end; traffic may exit it at any point its is accepted, dropped, rejected, etc

**Comment by ktsaou** [comment]
> Let me also add that there may be a need for marks that will not be saved/restored at all. This could be achieved by adding a nosave or norestore option to markdef. This will make the specific mark type be excluded from saving and restoring (save and restore will save and restore marks with a bitmask of only the mark types that should be saved and restored).

We could also support stateless mark types. This way, both the helpers and the save/restore should know what to do without any other configuration by the user and without changing the syntax of the helpers.

What do you think?

**Comment by philwhineray** [comment]
It seemed to me that the filter chain could be used by the user to change the mark and we should save it at the end. If the mark helpers are good enough then I guess that won't happen. I also see what you mean that we might not get to the save point anyway.

In any case I really like your suggestion to extending the mark definitions to specify the mark behaviour, including whether it is maintained for the connection and if it will be matched statelessly initially. I think that will keep the syntax clean and easy to use everywhere and it will be easy to extend if we ever need to.

**Comment by ktsaou** [comment]
Done.

**Comment by ktsaou** [comment]
@philwhineray is there something more related to this? Shall we close it?

**Comment by philwhineray** [comment]
I think we are done. Closed!
