### ISSUE TITLE
differentiate custom iptables options for in/out

### ISSUE THREAD

**Issue by maleadt** [ktsaou/firehol#53]
Using `custom` one can pass arbitrary arguments to iptables. I wanted to use this using the geopip module to restrict certain services to clients from specific countries, but for that I need to add the `--src-cc $COUNTRY` flag to the iptables command line.

As the name suggests, `--src-cc` only serves to match incoming traffic. In the current state, `custom` passes options to both the `in_` and `out_` chain, which doesn't work in case of geoip. I would need to add `--dst-cc` to the output rules instead.

It would be nice if one could specify different `custom` options for both the input and output chain of a certain rule (`custom_in` and `custom_out`?).

Alternatively, can I implement a `country` option which selects the proper option automatically? I don't know how modular firehol is.

**Comment by ktsaou** [comment]
Hi, I just pushed a version that supports this. Check the commit comment for details.

It would be great if you could test it and give us your comments.

**Comment by maleadt** [comment]
Working perfectly, thanks for the very fast response!

A minuscule remark: the `softwarning` contains a typo, overwritting instead of overwriting or overwritten.

**Comment by ktsaou** [comment]
fixed this too.
Thanks!

**Comment by ktsaou** [comment]
may I close this?

**Comment by maleadt** [comment]
Yes, this works fine!
