### ISSUE TITLE
Colour output going to pipe

### ISSUE THREAD

**Issue by philwhineray** [ktsaou/firehol#57]
When I pipe output from firehol into e.g. `less`, I see the terminal control codes now.

I am aware that this can be switched off with the `-nc` argument but I think we can also disable it automatically by using the bash `-t` test: http://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe

**Comment by ktsaou** [comment]
Did that.

https://github.com/ktsaou/firehol/commit/b083d6fa3c379bf62a11b03c16d340dc058596c0

Thanks.
