### ISSUE TITLE
Mixed mode src/dst

### ISSUE THREAD

**Issue by philwhineray** [ktsaou/firehol#58]
Up until recently it was possible to write e.g.

~~~~
router routera src "${UNROUTABLE_IPS}"
router routerb src not "${UNROUTABLE_IPS}"
~~~~

These no longer work, with not very helpful messages. I can write this instead, with the expected effect:

~~~~
router routera src4 "${UNROUTABLE_IPV4}" src6 "${UNROUTABLE_IPV6}"
router routerb src4 not "${UNROUTABLE_IPV4}" src6 not "${UNROUTABLE_IPV6}"
~~~~

I think we should either make the original to work again, or improve the error message, maybe by disallowing `src` and `dst` in `both` mode.

**Comment by ktsaou** [comment]
Thanks Phil,

fixed it.

**Comment by philwhineray** [comment]
Unfortunately it looks like the other got broken:

~~~~
router routera src4 "${UNROUTABLE_IPV4}" src6 "${UNROUTABLE_IPV6}"
router routerb src4 not "${UNROUTABLE_IPV4}" src6 not "${UNROUTABLE_IPV6}"
~~~~

Somehow IPv6 sources seem to overwrite the IPv4 versions, giving warnings and then an error in iptables for me.

**Comment by ktsaou** [comment]
@philwhineray I was hoping to avoid push/pop there. Anyway, it is back.

Also, this commit has an operational SYNPROXY ! The end of spoofing! The magic with SYNPROXY is that it allows to iptrap and blacklist only valid TCP clients. Spoofed IPs will not reach the iptrap and the blacklist...

If you don't find any other problems, close this please.

**Comment by philwhineray** [comment]
Excellent work on synproxy,

All looks OK now, thanks!
