### ISSUE TITLE
Listen lock workaround for SynProxy

### ISSUE THREAD

**Issue by pavel-odintsov** [ktsaou/firehol#76]
Hello, folks!

In this presentation Jasper perfectly described issue with listen lock in case of syn flood: http://people.netfilter.org/hawk/presentations/nfws2014/iptables-ddos-mitigation_RMLL.pdf

When we hit SYN flood attack to listened service we could expect really huge performance overhead. 

I checked this and could provide following numbers.

Syn flood to listened socket: 
```bash
TX eth5: 310 139 pkts/s RX eth5: 300584 pkts/s
TX eth5: 330 975 pkts/s RX eth5: 336856 pkts/s
```

Syn flod to not listened socket:
```bash
TX eth5: 2 235 582 pkts/s RX eth5: 2217774 pkts/s
TX eth5: 2 732 808 pkts/s RX eth5: 2685187 pkts/s
TX eth5: 2 784 552 pkts/s RX eth5: 2733840 pkts/s
```

As you can see difference is really amazing. 

But we could achieve this very big syn filtration performance for listened socket with workaround offered by Jasper.  He recommend to use NAT redirect and eliminate performance degradation due to this issue.

I suggest integration of this patch to FireHol.

It's really straightforward because you have almost all important code.

We could use configuration:
```bash
cat /etc/firehol/firehol.conf 
server_myhttp_ports="tcp/8081"
client_myhttp_ports="default"

ipv4 synproxy input inface eth5 dst 10.10.10.221 dport 80 redirect to 8081

interface eth5 wan
    server myhttp accept # packet filtering works with the real ports
    server icmp accept

interface eth0 my_local
    server ssh accept
    server icmp accept
``

We need create number of ports according to number of available cores on the server. All this ports should be listened by web server or another service.

Secondly, we need change current rule:
```bash
-A SYNPROXY2SERVER_IN -d 127.0.0.0/8 -i lo -p tcp -m tcp  --dport 8080-j ACCEPT
-A SYNPROXY2SERVER_OUT -d 127.0.0.0/8 -o lo -p tcp -m tcp  --dport 8080-j ACCEPT
-A in_wan -p tcp -m tcp --sport 1024:65535 --dport 8080-m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
```

To port range rules:
```bash
-A SYNPROXY2SERVER_IN -d 127.0.0.0/8 -i lo -p tcp -m tcp --match multiport --dports 8080:8087 -j ACCEPT
-A SYNPROXY2SERVER_OUT -d 127.0.0.0/8 -o lo -p tcp -m tcp --match multiport --dports 8080:8087 -j ACCEPT
-A in_wan -p tcp -m tcp --sport 1024:65535 --match multiport --dports 8080:8087 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
```

Secondly, we need add N rules for each cpu and feed traffic to this ports:
```bash
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 0 -j REDIRECT --to-ports 8080
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 1 -j REDIRECT --to-ports 8081
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 2 -j REDIRECT --to-ports 8082
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 3 -j REDIRECT --to-ports 8083
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 4 -j REDIRECT --to-ports 8084
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 5 -j REDIRECT --to-ports 8085
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 6 -j REDIRECT --to-ports 8086
-A SYNPROXY2SERVER_OUT -d 10.10.10.221/32 -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -m cpu --cpu 7 -j REDIRECT --to-ports 8087
```

Thank you so much!

**Comment by ktsaou** [comment]
Hi Pavel,

When designing synproxy for firehol, I studied, among other things, Jasper's presentation too.

On pages 15 and 19 Jasper says that this scalability issue has been fixed on kernel v3.15, so I concluded there is no reason to implement the work-around. Just upgrade your kernel.

Costa

**Comment by ktsaou** [comment]
By the way, I don't really have feedback for synproxy under firehol. I use it on production systems without issues, but I haven't heard experiences from others.

Do you use it? How? Do you have any issues with it?

Regards,

Costa

**Comment by melanor9** [comment]
its actually my quickfix for kernels prior to v3.
so yes. its no more needed.

**Comment by ktsaou** [comment]
Can I close this?

**Comment by pavel-odintsov** [comment]
Yes, we could close it!
