### ISSUE TITLE
link-balancer issue when specifying loop and timeout.

### ISSUE THREAD

**Issue by hcouplet** [ktsaou/firehol#77]
Just to let you know, that there is an issue with link-balancer when specifying the timeout with loop or boot parameter :

root@c00000c1office-voo:/sbin# link-balancer.in **loop 60**

FireHOL LinkBalancer $Id$
(C) Copyright 2015 Costa Tsaousis <costa@tsaousis.gr>
(C) Copyright 2015 Phil Whineray <phil@firehol.org>
FireHOL is distributed under the GPL v2+.
Home Page: http://firehol.org

-------------------------------------------------------------------------
Get notified of new FireHOL releases by subscribing to the mailing list:
    http://lists.firehol.org/mailman/listinfo/firehol-support/
-------------------------------------------------------------------------

Unknown option '60'
Waiting for 60 secs…

I fixed this by adding a shift after line 166 in link-balancer.in file : (this way the 60 is not passed anymore as parameter)

if [ "$1" = "loop" ]
then
 	shift
	secs="${1}"
	secs=$[ secs + 1 - 1 ]
	test "${secs}" = "0" && secs=300
	**shift**
	while [ 1 ]
	do
		$0 "${@}"
		echo "Waiting for $secs secs..."
		sleep $secs
	done
	exit 0
fi

**Comment by ktsaou** [comment]
thanks for reporting it.
if this is OK, please close it.

**Comment by hcouplet** [comment]
Thanks for your update. Now this is OK.
Closing this issue.
