### ISSUE TITLE
Help: Updated version in yum epel repo

### ISSUE THREAD

**Issue by 7imbrook** [ktsaou/firehol#79]
When will yum epel repo get the most up to date version? It's at 2.0.1, and I need 2.0.3 stable? I ran into a snag building from source and before I put too much effort into that I wanna see what the status is here.

**Comment by philwhineray** [comment]
Sorry, not sure how I failed to reply to this until now.

The firehol developers don't do the packaging for distributions - you will need to ask the packager direct. At least some if not all are on the mailing list, so you can start there if you cannot find a better place.
